# Generated by Django 3.0.8 on 2020-07-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.PositiveIntegerField()),
                ('student_name', models.CharField(max_length=60)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_password', models.CharField(max_length=60)),
            ],
        ),
    ]
