# Generated by Django 3.0.8 on 2020-07-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_api', '0002_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
