# Generated by Django 3.0.8 on 2020-07-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_api', '0003_auto_20200702_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breakfast',
            fields=[
                ('day_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('item1', models.PositiveIntegerField(null=True)),
                ('item2', models.PositiveIntegerField(null=True)),
                ('item3', models.PositiveIntegerField(null=True)),
                ('item4', models.PositiveIntegerField(null=True)),
                ('item5', models.PositiveIntegerField(null=True)),
                ('item6', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('day_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('item1', models.PositiveIntegerField(null=True)),
                ('item2', models.PositiveIntegerField(null=True)),
                ('item3', models.PositiveIntegerField(null=True)),
                ('item4', models.PositiveIntegerField(null=True)),
                ('item5', models.PositiveIntegerField(null=True)),
                ('item6', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lunch',
            fields=[
                ('day_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('item1', models.PositiveIntegerField(null=True)),
                ('item2', models.PositiveIntegerField(null=True)),
                ('item3', models.PositiveIntegerField(null=True)),
                ('item4', models.PositiveIntegerField(null=True)),
                ('item5', models.PositiveIntegerField(null=True)),
                ('item6', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
